### ISSUE TITLE
Import problem

### ISSUE THREAD

**Issue by yourash** [oflatt/bearlydancing#2]
bearlydancing/src/variables.py", line 37, in <module>
    ctypes.windll.user32.SetProcessDPIAware()
AttributeError: module 'ctypes' has no attribute 'windll'

**Comment by oflatt** [comment]
Ah, are you running on mac? I added a check to only call that function on windows. I'll test it out on a mac as soon as I can to make sure it works. Thanks!

**Comment by yourash** [comment]
Linux. I think the same solution 4 u.

**Comment by oflatt** [comment]
Does the most recent commit work? (If you want to play the game normally, make the exportmode variable in variables.py True.)

**Comment by yourash** [comment]
Works OK right now
